export const
  ADD_BOARD = 'ADD_BOARD',
  SUBMIT_BOARD = 'SUBMIT_BOARD',
  EDIT_BOARD = 'EDIT_BOARD',
  DELETE_BOARD = 'DELETE_BOARD',

  ADD_COLUMN = 'ADD_COLUMN',
  SUBMIT_COLUMN = 'SUBMIT_COLUMN',
  EDIT_COLUMN = 'EDIT_COLUMN',
  DELETE_COLUMN = 'DELETE_COLUMN',

  ADD_CARD = 'ADD_CARD',
  SUBMIT_CARD = 'SUBMIT_CARD',
  EDIT_CARD = 'EDIT_CARD',
  DELETE_CARD = 'DELETE_CARD',

  SET_CURRENT_BOARD_ID = 'SET_CURRENT_BOARD_ID'

